### ISSUE TITLE
GitHub has the Amazon links for tokenUrl and authorizationUrl and also uses localhost for redirectUrl

### ISSUE THREAD

**Issue by GroovinChip** [Clancey/simple_auth#13]
`this.tokenUrl = "https://api.amazon.com/auth/o2/token";
    this.authorizationUrl = "https://www.amazon.com/ap/oa";
`

`String redirectUrl = "http://localhost",`

**Comment by GroovinChip** [comment]
Thanks for fixing this so quickly!

**Comment by Clancey** [comment]
Thanks for reporting it! Amazing copy/paste failure while creating the providers.

**Comment by GroovinChip** [comment]
You're very welcome! One last question, is the redirect url supposed to be localhost?

**Comment by Clancey** [comment]
Yes and no. There is an embedded web browser. If you use it localhost is perfect. That is how the project originally worked. Then I defaulted to Chrome Tabs, and SFSafari.  At that point localhost no longer works.  I should have removed the redirect defaults then. You will notice I already fixed it and made the [breaking change commit](https://github.com/Clancey/simple_auth/commit/8683589678998623a47fa668d772cfc0f2a8523d) of making redirects required.

**Comment by GroovinChip** [comment]
I understand. Thanks so much for the explanation!

**Comment by GroovinChip** [comment]
Sorry, last last question - would you mind showing an example of how to use GitHub scopes with your package?

```
  final simpleAuth.GithubApi githubApi = simpleAuth.GithubApi(
    "github", "9020fb1eded8b2a9206f",
    "635a3c0c4513af8899339002fd20164182bc817c",
    "https://github.com/GroovinChip/Flutter-Community-Challenges",
    scopes: [
      "user"
    ],
  );
```

This gives the 'NoSuchMethodError: the method 'resetAuthenticator' was called on null' Exception

**Comment by GroovinChip** [comment]
I will definitely try it. I'll be back home in about an hour and I'll let you know how it goes

**Comment by Clancey** [comment]
If it works, I will publish to pub.

**Comment by GroovinChip** [comment]
So I need to pull down your repo to test, right?

**Comment by Clancey** [comment]
Or just copy [this](https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/providers/github.dart) into your project. I would rename it to GithubApi1 or something like that.

**Comment by GroovinChip** [comment]
alright I made a GithubApi1.dart file, and renamed the class accordingly. Changing it where I actually call the api gives me an error, though - `unidentified class simpleAuth.GithubApi1`

**Comment by GroovinChip** [comment]
Cloned your repo and pasted my code from above and it seems to work!
