### ISSUE TITLE
No such module 'SimpleAuth' in iOS build

### ISSUE THREAD

**Issue by Jon-Salmon** [Clancey/simple_auth#134]
When trying to use the AppDelegate.swift example code in my project, I'm getting a compile error of:

No such module 'SimpleAuth'

**Comment by Clancey** [comment]
New Version has been pushed!

**Comment by Jon-Salmon** [comment]
I'm afraid this is still not working. Building the example in /simple_auth_flutter/example throws the error.

**Comment by Gadda27** [comment]
@Jon-Salmon I'm having the same problem. Did you manage to fix it?

**Comment by Jon-Salmon** [comment]
@Gadda27 I think the proper fix for this requires a modification to the .podspec file for this module, but I worked around it by adding a bridging header to the flutter 'Runner' module

**Comment by hassansaleh31** [comment]
I'm having the same issue, can you explain more on how you managed to add a bridging header?

I'm not experienced in iOS development

**Comment by Tessalicious** [comment]
if you 

import simple_auth_flutter;

 instead then it lets you use SimpleAuthFlutterPlugin.check(url)
In my case it still wasn't working though. After authenticating it just went back to the login screen in the browser and never went back to the flutter app.
