### ISSUE TITLE
code for iOS swift

### ISSUE THREAD

**Issue by ziasultan2** [Clancey/simple_auth#149]
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
    return [SimpleAuthFlutterPlugin checkUrl:url];
}

THis is for objective c. I have swift file what will be the code for swift

**Comment by Clancey** [comment]
You can see a swift example as part of the extension: https://github.com/Clancey/simple_auth/blob/master/simple_auth_flutter/example/ios/Runner/AppDelegate.swift

**Comment by devon2018** [comment]
@Clancey I've tried using the example AppDelegate.swift and getting this `no such module 'SimpleAuth'`, let me know if there is any more details I can provide to help debug

**Comment by Nilesh-Chaudahri** [comment]
@devon2018  same error i am getting, have you got any solution ? please explain if you got

**Comment by Nilesh-Chaudahri** [comment]
@devon2018  you can refer this one https://stackoverflow.com/questions/66266152/simple-auth-flutter-on-ios-appdelegate-swift-import-change-fails-to-start
