### ISSUE TITLE
Incompatible with http 0.13.0

### ISSUE THREAD

**Issue by Vitaly-V** [Clancey/simple_auth#152]
Because simple_auth_flutter >=2.0.7 depends on simple_auth ^2.0.7 which depends on http >=0.11.0 <0.13.0, simple_auth_flutter >=2.0.7 requires http >=0.11.0 <0.13.0.
So, because app depends on both package_name ^1.0.0-nullsafety and simple_auth_flutter ^2.0.7, version solving failed.

**Comment by Vitaly-V** [comment]
https://github.com/Clancey/simple_auth/pull/153

**Comment by Vitaly-V** [comment]
Thanks for merging. But may I ask you to update pub.dev package version?

**Comment by mattia-venturini** [comment]
I found a compatibility problem with http 0.13.0

in simple_auth/lib/src/provders/keycloak.dart, line 55:
`var resp = await httpClient.post("${this.baseUrl}/auth/realms/${this.realm}/protocol/openid-connect/logout",`

`The argument type 'String' can't be assigned to the parameter type 'Uri'.`

**Comment by Vitaly-V** [comment]
@mattia-venturini this PR should fix it https://github.com/Clancey/simple_auth/pull/155

**Comment by Clancey** [comment]
Package is updated!
