### ISSUE TITLE
This site can't be reached: google api

### ISSUE THREAD

**Issue by matthewkooshad** [Clancey/simple_auth#16]
from comment on https://github.com/Clancey/simple_auth/issues/15 after it was closed:
final simpleAuth.GoogleApi googleApi = new simpleAuth.GoogleApi("google",
"992461286651-k3tsbcreniknqptanrugsetiimt0lkvo.apps.googleusercontent.com",
"http://localhost",
clientSecret: "avrYAIxweNZwcHpsBlIzTp04",
scopes: [
"https://www.googleapis.com/auth/userinfo.email",
"https://www.googleapis.com/auth/userinfo.profile"
]);

is this how i should update it with the latest change? i don't know what to use for the redirecturl.

and, i don't to the choose an acct screen with the latest..:
![image](https://user-images.githubusercontent.com/6706761/45063639-86db1600-b074-11e8-9f49-817281fca45f.png)

**Comment by Clancey** [comment]
The latest changes  do not effect this at all. This is caused by an issue on your device/emulator. Try going to https://accounts.google.com in Chrome on the device. See what happens.

**Comment by matthewkooshad** [comment]
thanks for your help. new to the emulator, i hadn't seen it perform in that way before. all is well after a closing and cold boot of it with your test project.
