### ISSUE TITLE
googleApi.getUserProfile(), Invalid argument(s): The source must not be null

### ISSUE THREAD

**Issue by matthewkooshad** [Clancey/simple_auth#17]
i no longer get the error about int with the example project's google api key, but with my own google api key, i am still getting the error reported here: https://github.com/Clancey/simple_auth/issues/15#issue-356986288

Invalid argument(s): The source must not be null

that error is caught in this try:
```
try {
                var user = await googleApi.getUserProfile();
                showMessage("${user.name} logged in");
              } catch (e) {
                showError(e);
              }
```
it fails with that before reaching the showMessage call, so it must be a problem somewhere in getUserProfile. what could i be missing with my google project?

![image](https://user-images.githubusercontent.com/6706761/45065090-e9d0ab00-b07c-11e8-9330-8189cf0de847.png)

![image](https://user-images.githubusercontent.com/6706761/45065099-ee955f00-b07c-11e8-8890-04b6008275d2.png)

**Comment by Clancey** [comment]
Is this iOS or Android? I tested it on iOS before publishing.

**Comment by matthewkooshad** [comment]
android.

also, i don't know if it matters, but clientSecret is provided in the example, but i only get a secret key provided by google if i do a client for a web application. if it's for an android application, as mine is, then they do not show a secret key.

**Comment by matthewkooshad** [comment]
if i leave out the clientSecret like in the first instance, though still using your test project key, i also get The source must not be null.

```
final simpleAuth.GoogleApi googleApi = new simpleAuth.GoogleApi("google",
      "992461286651-k3tsbcreniknqptanrugsetiimt0lkvo.apps.googleusercontent.com",
      scopes: [
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile"
      ]);


  final simpleAuth.GoogleApi googleApi2 = new simpleAuth.GoogleApi("google",
      "992461286651-k3tsbcreniknqptanrugsetiimt0lkvo.apps.googleusercontent.com",
      clientSecret: "avrYAIxweNZwcHpsBlIzTp04",
      scopes: [
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile"
      ]);
```

**Comment by matthewkooshad** [comment]
![image](https://user-images.githubusercontent.com/6706761/45066215-ecce9a00-b082-11e8-9da8-69088b2b206e.png)

671805870243-a3sc7c4i2cjbo2vb05gch7dba05bnvn6.apps.googleusercontent.com

so do i create a web application client as well and use the secret key from that with the client id for android?

**Comment by Clancey** [comment]
So client_secret is not required. If your doing Android with the right key signing, Don't pass in a client_secret.

**Comment by matthewkooshad** [comment]
i'll try to remove the clientSecret and check on my signing-cert to make sure it is being correctly generated.

for the keys you provided with the example, how did you get a secret key for the android client?

**Comment by Clancey** [comment]
The secret in the sample is a web token.

**Comment by matthewkooshad** [comment]
could you tell me how to generate another one? as noted above, if i do not provide that web token, then it is a second way that i can produce the error above.

**Comment by Clancey** [comment]
Sure, you can create one here: https://console.developers.google.com/apis/credentials

**Comment by matthewkooshad** [comment]
if i use both the secret key (that's what you're calling the web token?) and the client id from the above web client credential creation, then i get the below issue, which i know you've mentioned that we must use a android client type credential:
![image](https://user-images.githubusercontent.com/6706761/45100924-fcd09300-b0ef-11e8-878d-ab4f7fd8278b.png)

so, could you please clarify the retrieval of the "web token" from that credential creation page and how to use it in collaboration with the android client type credentials? thanks!

**Comment by matthewkooshad** [comment]
i feel like the question is simple, so i'm sorry if i have bothered you in trying to understand why my generated keys/tokens do not work and your test project's does.

that's pretty much of my questions above are trying to figure out. to solve the below from the OP on this issue.

> i no longer get the error about int with the example project's google api key, but with my own google api key, i am still getting the error reported here: https://github.com/Clancey/simple_auth/issues/15#issue-356986288

**Comment by fromlabs** [comment]
@matthewkooshad I'm using this plugin with Google and Office365 authentication (with custom OAuthApi extension). 
I figured out debugging the Dart code of the plugin. Based on the 1.0.6 code I suggest you the following breakpoints:

- Authentication code request [SimpleAuthFlutter.showAuthenticator:27]
- Authentication code response [WebAuthenticator.checkUrl:26]
- Access token request: [OAuthApi.getAccountFromAuthCode:112]
- Access token response: [SimpleAuthFlutter.showAuthenticator:118]

Hope it helps!

**Comment by matthewkooshad** [comment]
@fromlabs thanks for the advice. 

//clientSecret is "native"
    var postData = await authenticator.getTokenPostData(clientSecret);

"{
  "error": "invalid_client",
  "error_description": "Unauthorized"
}"

**Comment by Clancey** [comment]
Are the exceptions getting swallowed? I hope they would bubble up. If they are not bubbling up, that needs fixed.

**Comment by matthewkooshad** [comment]
@Clancey here's how it appears on the frontend:
![image](https://user-images.githubusercontent.com/6706761/45909816-d4bc8180-bdc9-11e8-887e-dbfceb4846e5.png)

**Comment by matthewkooshad** [comment]
@Clancey the exception is not getting swallowed. here's what it looks like in the catch:
![image](https://user-images.githubusercontent.com/6706761/45909905-92477480-bdca-11e8-9c26-8a4a486672d7.png)
what am i doing wrong??

**Comment by matthewkooshad** [comment]
> If your doing Android with the right key signing, Don't pass in a client_secret.
@Clancey i provided the key to google for the client id generation, but i don't know how to provide that same key to the flutter app. that might be the issue causing the 401.
also, you'll notice above where i gave some screenshots, demonstrating that i couldn't produce a client_secret web token for a client that's to be used for Android. and, it complains if i tried to use a client that's to be used for WEB. i don't know how you achieved that :man_facepalming:

**Comment by fromlabs** [comment]
@Clancey I'm generating a Google client ID of type "other". After creation the wizard provides you a client_id and client_secret that you can use:
```
final googleApi = new GoogleApi(
	'google',
	'12321312312312321-sasdasdasdsdssdasdasaddsasda.apps.googleusercontent.com',
	clientSecret: 'xyxyxyxyxyyxyxyxyxyxyx',
	scopes: ['email', 'profile'],
);
```

**Comment by matthewkooshad** [comment]
@fromlabs why would anyone use Android type? i was not able to get this api to work with using the Android type. to which i am guessing, i need to do something in the Android type case with the json file that Google provides.

**Comment by fromlabs** [comment]
@matthewkooshad I'm using this plugin because I was been able to implement the Office365 authentication with little effort. Currently for Google authentication I'm using [google_sign_in](https://pub.dartlang.org/packages/google_sign_in) plugin which uses native Google library and works with both Android and iOS type client id.

**Comment by matthewkooshad** [comment]
thanks @fromlabs , i'll look more into that package.

**Comment by Clancey** [comment]
It's on my TODO, to support those packages as an option dependency. That will allow you to use them for authentication, without changing any additional code or Api requests.
