### ISSUE TITLE
More a question than an issue

### ISSUE THREAD

**Issue by samgithub-duplicate** [Clancey/simple_auth#2]
Please excuse my ignorance.  Exactly where in a DART file do we put the 'generator'
@GoogleApiDeclaration("GoogleTestApi","client_id",clientSecret: "client_secret", scopes: ["TestScope", "Scope2"])
abstract class GoogleTestDefinition {
  @Get(url: "https://www.googleapis.com/oauth2/v1/userinfo?alt=json")
  Future<Response<GoogleUser>> getCurrentUserInfo();
}

I  have the following 2 imports:
import 'package:simple_auth/simple_auth.dart';
import 'package:simple_auth_generator/simple_auth_generator.dart';

BUT
void getUserCredentials() async {
  var api = new GoogleTestApi("google");
var user = await api.getCurrentUserInfo();
} 
does not recognize GoogleTestAPI

**Comment by Clancey** [comment]
Here is an example: 
https://github.com/Clancey/simple_auth/blob/master/simple_auth_flutter_example/lib/api_definitions/youtubeApi.dart
and 
https://github.com/Clancey/simple_auth/blob/master/simple_auth_flutter_example/lib/api_definitions/azureAdTestApi.dart

No need to import the generator. You just run it.

**Comment by samgithub-duplicate** [comment]
Thanks, James.

I just tried the youtube sample
https://github.com/Clancey/simple_auth/blob/master/simple_auth_flutter_example/lib/api_definitions/youtubeApi.dart

(creating a directory api_definitions and copying youtubeApi.dart into it)

I then run
flutter packages pub run build_runner build

Unfortunately, it does not generate the class.
THis is really not your issue.  I just jumped int DART/flutter just 2 months ago (from the ASPnetCore C# environment)

I'll try again once i have learned more DART/flutter.

THANKS again

Sam
________________________________

**Comment by Clancey** [comment]
So this works just like json_serializable:  
Read the doc on json https://flutter.io/json/ specifically the json_serializable section.  It will explain how to setup things for the generator. Make sure you also have added this to your pubspec.yaml
```yaml
dev_dependencies:
  simple_auth_generator: 
  build_runner: ^0.8.0
```

**Comment by samgithub-duplicate** [comment]
Hi James:

Can I assume that the claims provided in the simple_auth token are all consistently mapped for the supported providers:

a) Name (either given_name, surname) or -- something similar
b) email

Those are the 2/3 claims I am particularly interested in.  I need to access those on the server side  --- At least for Azure, Google, Microsoft Live, Facebook.

Thanks

**Comment by Clancey** [comment]
That is not something simple auth deals with. I do not parse or verify the tokens aside from getting them from the auth servers.  However, most tokens have that data encoded in the token. And you should be able to use that token serverside to make a request for the user. It is just a standard valid token.

**Comment by samgithub-duplicate** [comment]
Ok Thanks.

Sam

________________________________

**Comment by Jeremywhiteley** [comment]
Sam,  we will both need to find a plugin that will decode the jwt token that is returned.
