### ISSUE TITLE
Android Callback scheme not recognised?

### ISSUE THREAD

**Issue by willladislaw** [Clancey/simple_auth#21]
Neither of the following working for me. 

Redirect url displayed in browser without returning to the app.

Server redirect url: https://example.com/secure 

1.
<activity android:name="clancey.simpleauth.simpleauthflutter.SimpleAuthCallbackActivity" >
    <intent-filter android:label="simple_auth">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="com.example:/secure" />
    </intent-filter>
</activity>

2.
        <activity android:name="clancey.simpleauth.simpleauthflutter.SimpleAuthCallbackActivity" >
            <intent-filter android:label="simple_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https"
                    android:host="example.com"
                    android:pathPrefix="/secure"/>
            </intent-filter>
        </activity>

3. 
        <activity android:name="clancey.simpleauth.simpleauthflutter.SimpleAuthCallbackActivity" >
            <intent-filter android:label="simple_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https"
                    android:host="*.example.com"
                    android:pathPrefix="/secure"/>
            </intent-filter>
        </activity>

Full AndroidManifest.xml

manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.example">

    
    <uses-permission android:name="android.permission.INTERNET"/>

    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="example"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="clancey.simpleauth.simpleauthflutter.SimpleAuthCallbackActivity" >
            <intent-filter android:label="simple_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https"
                    android:host="*.example.com"
                    android:pathPrefix="/secure"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by Clancey** [comment]
By default, you cannot use http/https redirects. I just updated the [readme](https://github.com/Clancey/simple_auth#redirect) to clarify this.
