### ISSUE TITLE
Deprecated IOS line in README.md 

### ISSUE THREAD

**Issue by willladislaw** [Clancey/simple_auth#22]
README.md is no longer valid for swift 4 (see below). 

Using line from README.md causes build to fail:

Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ~/flutter_workspace/example/ios/Runner/AppDelegate.swift:20:1: error: expected declaration
    - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
    ^
    ~/flutter_workspace/example/ios/Runner/AppDelegate.swift:6:13: note: in declaration of 'AppDelegate'
    @objc class AppDelegate: FlutterAppDelegate {

import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
    return [SimpleAuthFlutterPlugin checkUrl:url];
}

}

Tried changing above to following: 'Use of unresolved identifier 'SimpleAuthFlutterPlugin''. 

override func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
    return SimpleAuthFlutterPlugin.checkUrl(url)
}

**Comment by Clancey** [comment]
That code snippet is Obj-C. It would need to be translated to Swift.

**Comment by willladislaw** [comment]
I tried the following: 'Use of unresolved identifier 'SimpleAuthFlutterPlugin''.

override func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
return SimpleAuthFlutterPlugin.checkUrl(url)
}

**Comment by Clancey** [comment]
It looks like SimpleAuth needs a bridge header to make it accessible to Swift. I don't have time to look at it today. But a quick google search made it look easy. If you want to take a stab at it, a pull request would be great!
