### ISSUE TITLE
googleApi: determine authenticated without going through authentication process when not authenticated

### ISSUE THREAD

**Issue by matthewkooshad** [Clancey/simple_auth#24]
how can i get if the app user has authenticated with google without sending the user to the google authentication page (choose a google account page)? thanks!

**Comment by Clancey** [comment]
So if everything works right you shouldn't need to do anything. Test on a device. Login, then call login again. It will not present the UI. If tokens are cached and are valid, the UI will not be presented until the credentials are expired, and for some reason cannot be refreshed. For most providers this means you never show a login again, unless they log out.

**Comment by matthewkooshad** [comment]
@Clancey 
"Login, then call login again" -- before the initial "Login" you've said to do, how can i check if the user has Logged in? i only want to send the user to the Login page to Login if they are not Logged in.
