### ISSUE TITLE
googleApi: determine Logged In without going through Login process when user is not Logged In

### ISSUE THREAD

**Issue by matthewkooshad** [Clancey/simple_auth#25]
> Login, then call login again. It will not present the UI. If tokens are cached and are valid, the UI will not be presented until the credentials are expired

the problem about the above is that before the initial "Login" @Clancey said to do [(24),](https://github.com/Clancey/simple_auth/issues/24), how can i check if the user has Logged in (without sending the user to go Login)? i only want to send the user to the Login page to Login if they are not Logged in. thanks!

**Comment by matthewkooshad** [comment]
if the app terminates, then the UI is getting presented. so, it seems it's only cached while the app is running in the foreground and background, but once the app is closed, then it will present the UI again for the user to choose the google account to login with. so, this is a 2nd problem.

so, for the first problem, we store on the device's user prefs that the user has a google account used before.

but, for the the 2nd issue stated in this comment, how do i cache the tokens and check for valid **without** going to the UI again for the user to choose their account again? this is the experience i am seeing when using googleApi.authenticate()

**Comment by Clancey** [comment]
I cannot duplicate this. Using the sample, on iOS and Android if I log into an account. next time I press login the UI is not shown. What platform are you trying this on? iOS Simulator has had a bug for years, if you don't specify entitlements it will not let you securely save tokens. So this could happen on the iOS Simulator.

**Comment by matthewkooshad** [comment]
Using it on an android emulator and android device gives me the same
results that I described when closing the app and closing it from running
in the background. You are closing its task too?

**Comment by Clancey** [comment]
I have been debugging. Starting and stoping the debugger. That kills the processes

**Comment by Clancey** [comment]
If you look at the authenticate code, it loads the cached account. If it is still valid, it returns and never presents the UI: https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/oauth/oauthApi.dart#L60-L72

**Comment by Clancey** [comment]
I would recommend cloning the source, putting some breakpoints in there and see what happens for you.

**Comment by matthewkooshad** [comment]
Sounds good James, I'll do just that and report back.

**Comment by matthewkooshad** [comment]
@Clancey you're right about that example performing as i'm looking for. i don't know what i'm doing wrong.

**Comment by Clancey** [comment]
What provider are you using? A custom one? If so, it is most likely not setting the RefreshToken or the Expiration on the account.

**Comment by matthewkooshad** [comment]
sorry, i don't understand to answer that. but, i did want to report back in case someone encounters this problem as well. for me, it was a scope issue of where this instance was declared:
final simpleAuth.GoogleApi googleApi = new simpleAuth.GoogleApi(,,,
when i relocated it to the same function where the below statement happens, then it was working as the example, giving the desired result. i think i'm fine with the result of the code on this, so i will not be investigating why for now.
var user = await googleApi.getUserProfile();
