### ISSUE TITLE
Question - Authentication Success Message

### ISSUE THREAD

**Issue by edwino26** [Clancey/simple_auth#28]
Hi there,

I am a pretty new to programming and started learning Flutter recently. Apologies if my question is way too basic or does not belong under this thread. 

I am running simple_auth_flutter and am testing authentication to Instagram. I am able to get the authentication screen and Instagram directs me to the callback URI. Once there I was expecting to get the showMessage success:

 var success = await api.authenticate();
      showMessage("Logged in success: $success");

I am getting stuck at the callback screen with only a cancel button, which cancels the authentication. I do not see the success message. 

I basically would like to know how I can go back to main.dart once the user is authenticated and grab the authorization uri to get Instagram's token and be able to access the user's information.

Your help would be much appreciated.

Thanks in advance!

**Comment by Clancey** [comment]
My guess is, it is the redirect.  If you don't do a proper redirect to something that opens the app back up, it won't work. https://github.com/Clancey/simple_auth#redirect

**Comment by Clancey** [comment]
Going to close this assuming it was the redirect. Reopen if you need too.

**Comment by ricamgar** [comment]
Hi, I'm trying to set the redirect as you explain in the docs, but it is not possible to add a custom scheme on Instagram Developer 
![image](https://user-images.githubusercontent.com/927648/49688958-1aabfa80-fb1a-11e8-8375-2852194b2430.png)

I think that's the reason why I get always the error `Redirect URI does not match registered redirect URI` on the browser after successful login.

On the manifest I have the intent filter with:
`<data android:scheme="com.myapp.foo" />`

And in the code the InstagramApi with the parameter `redirectUrl: "com.myapp.foo"`

Am I doing anything wrong? Thanks!

**Comment by Clancey** [comment]
@ricamgar if Instagram will not let us use a non http redirect, It can be set to something like localhost.  Then try this gist: https://gist.github.com/ for the API. This will let us detect localhost. 

If that API works for you, please let me know and I will get it updated!

**Comment by ricamgar** [comment]
Hi @Clancey , I think the link to the gist is wrong. Could you post it again please? Thanks!

**Comment by Clancey** [comment]
Sorry about that fixed
