### ISSUE TITLE
App seems to not getUserProfile

### ISSUE THREAD

**Issue by samgithub-duplicate** [Clancey/simple_auth#3]
I am following the  examle in "simple_auth_flutter_example"

When I get to 

 var user = await googleApi.getUserProfile();
The app shows the Google Sign-in page.  
After 'signing' in nothing seems to happen. I have a breakpoint after the getUserProfile.  It does not get hit.  

Sam

**Comment by Clancey** [comment]
on iOS or Android?  Did you follow the Callback parts from the readme in [iOS](https://github.com/Clancey/simple_auth#ios) and [Android](https://github.com/Clancey/simple_auth#android-manifest)?

**Comment by samgithub-duplicate** [comment]
I have double-checked and set everything up meticulously.  What I notice is that if I use your sample (in   https://github.com/Clancey/simple_auth/blob/master/simple_auth_flutter_example/lib/main.dart)

i.e (using the credentials in the sample link above: (blocked off in asterisks below. I get the sign in page BUT after signing-in, I get an error "invalid credentials". If I use **MY** app credentials I do NOT get the sign-in page, but I get an error "Custom Schemes are not allowed for Web Client Type"
*************


final simpleAuth.GoogleApi googleApi = new simpleAuth.GoogleApi("google",
      "992461286651-k3tsbcreniknqptanrugsetiimt0lkvo.apps.googleusercontent.com",
      clientSecret: "avrYAIxweNZwcHpsBlIzTp04",
      scopes: [
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile"
      ]);
********************************************
  
Sam

**Comment by samgithub-duplicate** [comment]
Thanks for the 1.0.1 update.  In the meantime, I decided to check out your **Facebook** implementation. using simple_auth_flutter 1.0.1
After logging in, I get an error **localhost refused to connect**.

**Comment by Clancey** [comment]
You can't use local Host as a redirect unless you use the embedded browser. It is off by default. You need to use a redirect with a custom scheme for your app.

**Comment by samgithub-duplicate** [comment]
James, please close this issue.  I found a way to authenticate with Facebook.  I'll be creating another issue for Microsoft Live Acounts
