### ISSUE TITLE
Another success/callback (support) question

### ISSUE THREAD

**Issue by abjorck** [Clancey/simple_auth#30]
I got it almost working - the custom callback is called and the authCode is set, completer is completed, but then I also get an error when it from somewhere tries to parse some html, and the completer is then also trying to cancel, but future is already complete.. 

![screen shot 2018-10-08 at 16 44 34](https://user-images.githubusercontent.com/569069/46615995-e1efa500-cb19-11e8-9362-2267404ada76.png)

`2018-10-08 16:44:30.924 6759-6834/com.example.simpleauthflutterexample E/flutter: [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
    FormatException: Unexpected character (at line 3, character 1)
    <!DOCTYPE html>
    ^
    
    #0      _MyHomePageState.login (file:///Users/bjorck/Projects/safe/simple_auth/simple_auth_flutter_example/lib/main.dart:401:7)
    <asynchronous suspension>
    #1      _MyHomePageState.build.<anonymous closure> (file:///Users/bjorck/Projects/safe/simple_auth/simple_auth_flutter_example/lib/main.dart:135:15)
    #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
    #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
`
Any hint on how to debug what that is?

**Comment by Clancey** [comment]
What are you authenticating against? Nothing should be passing in HTML, only json.  Please let me know how to reproduce and I can take a look!

**Comment by abjorck** [comment]
Yeah I think it's strange too. Using azure (b2c) ad. I'll see if I can get
something reproducible or put some logging in.

**Comment by Clancey** [comment]
I am guessing it is blowing up [here.](https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/oauth/oauthApi.dart#L118) . I would put a break point here and read what the Body is. I bet it has a full exception.

**Comment by Jeremywhiteley** [comment]
I doubt this is related, but If you are using Azure AD B2C they rolled this out in the last few weeks. 

https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin

**Comment by abjorck** [comment]
ah probably maybe have the wrong token url and it gets a 404 or something
