### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by Belzeb78** [Clancey/simple_auth#36]
Hi, 
I've a callback issue, I'm unable to catch the callback when I try to log on Teamsnap.
Teamsnapp need a https url as callback and I'm not able to catch it with simpleauthflutter.

Here is my Android Manifest:
```
 <activity android:name="clancey.simpleauth.simpleauthflutter.SimpleAuthCallbackActivity" >
            <intent-filter android:label="simple_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https://com.test.testsimpleauthflutter/redirct" />
            </intent-filter>
        </activity>
```

I understood that https is unusable, but have you an idea on the way to follow to use it?

**Comment by Clancey** [comment]
The issue is your Redirect starts with `https://`  you should instead change it to something like `com.test.testsimpleauthflutter://redirct`  The [Readme](https://mselite.microsoft.com/programs/368) has more details.
