### ISSUE TITLE
redirect url must be absolute on Facebook

### ISSUE THREAD

**Issue by gofur** [Clancey/simple_auth#37]
i have problem on login with facebook 
"redirect url must be absolute on Facebook"

**Comment by Clancey** [comment]
What redirect are you passing in?

**Comment by gofur** [comment]
https://m.facebook.com/dialog/oauth/?client_id=clientId&response_type=code&redirect_uri=redirect

**Comment by gofur** [comment]
@Clancey thanks i know what is problem.. i must setup application id on facebook developers..
