### ISSUE TITLE
App sits on redirect page in browser

### ISSUE THREAD

**Issue by gviddy** [Clancey/simple_auth#4]
Hey,

Do you have an example for OAuthApi ??

I am trying to connect to Meetup (Android currently). It shows the login page, etc. I successfully login and it then shows the redirect page and just sits there, in the browser. Never exits back to the app.

Is there something i am missing ?

**Comment by Clancey** [comment]
So there are two styles of authentication. Embedded and CustomTabs. It defaults to CustomTabs. You need to change the redirect, and setup the redirect just like the built in example: https://github.com/Clancey/simple_auth/blob/master/simple_auth_flutter_example/android/app/src/main/AndroidManifest.xml#L38-L44

Or you can use the embedded browser by setting useEmbeddedBrowser  to true: https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/api/webAuthenticator.dart#L10
