### ISSUE TITLE
Redirect scheme AzureAd failing

### ISSUE THREAD

**Issue by akeblom** [Clancey/simple_auth#41]
I have configured a callback scheme as follows:

```
<data android:scheme="com.foo.app" />
 <data android:host="auth" />

```
which should translate to com.foo.app://auth

I get to login the login screen ok. But after submitting the login form I get a popup which says:
_Exception: Unable to get an AuthToken from the server._

I did some debugging and found that I get the following error in 

AzureADAuthenticator._redirectUri.origin

_Unhandled exception: Bad state. Origin is only applicable to schemes http and https: com.foo.app://auth
SimpleUri.origin(dart:core/uri.dart4257:7)_

**Comment by Clancey** [comment]
What version of Simple Auth are you on? Does it happen in the sample?  I cannot duplicate it. I even tried ```var uri =Uri.parse("com.foo.app://auth");``` in the sample startup to try and duplicate it.

**Comment by Clancey** [comment]
That is really odd, I just published a 2.0.0 version. Can you check it there? I really cannot duplicate this. And I know other people have successfully used this to login. Any way you can debug and see if anything strange is happening? I would love to get this fixed.

**Comment by akeblom** [comment]
Yeah. Really strange. But if you read the documentation on uri.origin. It actually states that any protocol other than http and https is invalid. But I didn't find any usage of that property. Will test the new version soon.

Den 9 nov. 2018 22:54 skrev James Clancey <notifications@github.com>:

That is really odd, I just published a 2.0.0 version. Can you check it there? I really cannot duplicate this. And I know other people have successfully used this to login. Any way you can debug and see if anything strange is happening? I would love to get this fixed.

**Comment by Clancey** [comment]
It is really strange.  I did another local check forcing it like this:

```
    var uri =Uri.parse("com.foo.app://auth");
    var uri2 =Uri.parse("com.foo2.app2://auth2");
    var sameHost = uri.host == uri2.host;
```

Still no error.

**Comment by Clancey** [comment]
Also, that error mentions origin. Only host is called

**Comment by akeblom** [comment]
Strange. Will do some testing with the new version today. On another note. Is there some way to add additional query parameters. The Azure service I am calling needs a parameter called "p" which is the policy to be used. This is a required parameter. https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code

**Comment by akeblom** [comment]
Tried version 2.0.0 and now the checkUrl-method works fine.
