### ISSUE TITLE
Unable to fetch cached account from Dropbox provider

### ISSUE THREAD

**Issue by brettpappas** [Clancey/simple_auth#45]
I have been trying to get this working with Dropbox but I keep running into problems. The one I am stuck on now is that after I have authenticated and allowed access to my app - I keep getting prompted to allow access whenever I make an API call.

I believe the problem is with `loadAccountFromCache()`. The method is able to retrieve the credentials from authStorage but it fails when it gets to `getAccountFromMap<T>(data)`.

Here is the error I see:
```
I/flutter (13160): NoSuchMethodError: The getter 'iterator' was called on null.
I/flutter (13160): Receiver: null
I/flutter (13160): Tried calling: iterator
```

I will continue to hunt for why this is happening but I am struggling to understand why it gets tripped up here. I tested it using Google as the provider just to make sure my workflow wasn't missing a step.

**Comment by brettpappas** [comment]
Okay, I think the problem is with the dropbox provider overriding the `getAccountFromAuthCode` method without setting the `scope`. 

I just set it to an empty list which seems to fix it for me. I can submit another PR unless you think there is a better way to handle this somewhere else.

**Comment by Clancey** [comment]
It requires scopes even if it's empty? There is already a scope property. Right now it is only passed in if the scopes are not empty. For Dropbox just overriding the method and forcing it to use the scopes should be good. Sorry for this. I spent most my time on the core lib. I quickly ported over the providers from my c# version. For the most part they work perfectly.
