### ISSUE TITLE
Request AppDelegate.swift

### ISSUE THREAD

**Issue by cristianbregant** [Clancey/simple_auth#52]
Hi!
I just wanted to know if it was possible to have the swift code for the AppDelegate.swift and not only the AppDelegate.h since if you start the project with swift enabled in android studio it will provide only the swift one. 
Thanks!

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
      return [SimpleAuthFlutterPlugin checkUrl:url];
  }
```

**Comment by Clancey** [comment]
Yes you can. I even include a sample: https://github.com/Clancey/simple_auth/blob/master/simple_auth_flutter/example/ios/Runner/AppDelegate.swift

**Comment by cristianbregant** [comment]
Ok perfect! Thank you!

**Comment by hassansaleh31** [comment]
I tried this and got this error:
`No such module 'SimpleAuth'`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.3 19D76, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.2)
[✓] Connected device (1 available)

• No issues found!
