### ISSUE TITLE
Exception while loading account from cache

### ISSUE THREAD

**Issue by trevorwang** [Clancey/simple_auth#54]
I was testing whether this lib can cache the azure ad authentication. I saw safari page was opened every time the application was restarted.

I looked into this issue, and found that there was an exception when `getAccountFromMap` was invoked.

```
  Future<T> loadAccountFromCache<T extends Account>() async {
    var json = await _authStorage.read(key: identifier);
    if (json == null) return null;
    try {
      var data = Convert.jsonDecode(json);
      return getAccountFromMap<T>(data);
    } catch (exception) {
      print(exception);
      return null;
    }
  }

  getAccountFromMap<T extends Account>(Map<String, dynamic> data) =>
      Account.fromJson(data);
```

> "NoSuchMethodError: The getter 'iterator' was called on null.
> Receiver: null
> Tried calling: iterator"

<img width="1104" alt="screen shot 2018-12-25 at 11 04 02 pm" src="https://user-images.githubusercontent.com/121966/50424074-9ab3bd80-0899-11e9-806d-bf6b192c4fe1.png">

**Comment by Clancey** [comment]
Closing this since it has been merged in.
