### ISSUE TITLE
Dropbox API: cancelled exception

### ISSUE THREAD

**Issue by vishaldhudum** [Clancey/simple_auth#58]
I am trying to authenticate user on Dropbox. The deep link and login to Dropbox account works fine, the user gets redirected to Dropbox website and after login allows all necessary prompts but gives cancelled exception after that. [Here](https://github.com/vishaldhudum/dropboxAuth) is the sample project.

I have included this in Android manifest

        <activity android:name="clancey.simpleauth.simpleauthflutter.SimpleAuthCallbackActivity" >
            <intent-filter android:label="simple_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="com.googleusercontent.apps.682823335381-iba20i3fst8298mrn5c1ov052sg40v2g" />
            </intent-filter>
        </activity>

**Comment by vishaldhudum** [comment]
I have tried following 
1. updated `<data android:scheme="dropboxauth.page.link/dropboxauth" />` gives cancelled exception.
2. cannot add "myAwesomeApp12345" in dropbox Redirect URIs as it gives error "You must provide a proper URI with an authority or path component", so added `https://myAwesomeApp12345` and `<data android:scheme="myAwesomeApp12345" />` which gives error page saying "site can't be reached".
3. similar is the case for `http://localhost`

Have pushed the code if you wish to check, [here ](https://github.com/vishaldhudum/dropboxAuth/commit/8d8e0e5f66e68490076997e5b1247932a7199170)are the changes

and below urls are added in this dummy account
![image](https://user-images.githubusercontent.com/13764136/51588033-ce215080-1f08-11e9-8cb4-0890d8eef216.png)

**Comment by Clancey** [comment]
Can you put "myAwesomeApp12345://dropboxAuth"? What you are doing is registering a way for the Android to redirect to your app. Https is already taken. And when you do ``<data android:scheme="myAwesomeApp12345" />``` you are telling android that you want to open for all urls that start use myAwesomeApp12345, i.e ```myAwesomeApp12345://dropboxAuth```

**Comment by vishaldhudum** [comment]
With [these](https://github.com/vishaldhudum/dropboxAuth/commit/22cde01b3935ca34797fc6c576d1c5b3ca0913bb) changes and `myAwesomeApp12345://dropboxAuth` registered in dropbox redirect URI, after login to dropbox account it gets stuck on page where user needs to allow access to files in dropbox, though the user gets linked on tapping Allow.

**Comment by Clancey** [comment]
It looks like I gave you bad advice. The Scheme needs to be all lower case. Android forces it.  So register with "myawesomeapp12345"

**Comment by Clancey** [comment]
I just pushed a new version. It will work around the casing issue.

**Comment by vishaldhudum** [comment]
Lowercase URL worked. Thank you.

Though after updating `simple_auth: ^2.0.1` & `simple_auth_flutter: ^2.0.1` in pubspec.yaml didn't worked with `myAwesomeApp12345://dropboxAuth`

**Comment by vishaldhudum** [comment]
> how can I get `accountId` of the dropbox user. I get `token` and `userdata`, but in `userdata` I couldn't find any `accountId`.

@Clancey 
Any help on this please.
