### ISSUE TITLE
Logo Design Offer For Simple Auth

### ISSUE THREAD

**Issue by iqbalhood** [Clancey/simple_auth#6]
Hello Sir. I'm a UI/UX and Graphics Designer. who has contacted you via email last week.
This is my logo proposal for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it

![simpleauth](https://user-images.githubusercontent.com/1563756/43763127-22f4a59c-9a54-11e8-8485-c8b940b96dd4.jpeg)

Thanks before.
Regards,
@iqbalhood

**Comment by Jeremywhiteley** [comment]
This logo is awesome. Very clean!

**Comment by iqbalhood** [comment]
Hi, @Clancey Can You Give me some credit on Readme.md.?
Like This -> Thank's For the logo @iqbalhood
or on another format 

Thanks :)

**Comment by Clancey** [comment]
Yes! Want to send a pull request?

**Comment by iqbalhood** [comment]
Of course! this is the pull request

https://github.com/Clancey/simple_auth/pull/9
