### ISSUE TITLE
Integrating with keycloak.

### ISSUE THREAD

**Issue by intako** [Clancey/simple_auth#62]
Hello, we're using _keycloak_ for authentication/autherization that uses openid connect protocol.
I'm trying to implement authorization for flutter app with simple auth, but don't have any understanding how to do that. I haven't found any discovery function for that.

Small guide about integrating with custom providers would be really appreciable.
Thanks in advance.

**Comment by Clancey** [comment]
I agree, this needs more documentation. Over all it's really simple to add new things in. Standard OAuth, is really as simple as passing the right arguments in. https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/providers/amazon.dart Some things do very custom things like [Dropbox](https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/providers/dropbox.dart)

Feel free to ask more questions if you run into anything specific or if you don't understand something. You can also ask in [Gitter](https://gitter.im/simple_auth/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by Clancey** [comment]
Now that you have successfully integrated, any thoughts on what should be added to the documentation?

**Comment by intako** [comment]
I think just little example of connecting simple auth with custom identity provider would be helpful, just basic stuff. As I mentioned before, I was integrating with _keycloak_, so I made it using _AmazonApi_ class as example, just replaced all necessary arguments with parameters from response of keycloak discovery url and all is working now.

**Comment by dylan-dinh** [comment]
@intako hey i'm using keycloak as well for linkedin facebook and google do you have a sample like the AmazonApi you took as example ?

**Comment by IRuFFeYI** [comment]
@intako Hey i try to realise an authentication flow with Keycloak. It doesn't work atm. Could you maybe post your solution here?

**Comment by dylan-dinh** [comment]
I finally used an other package to do it.
But the package wouldn't work as dependencies so I downloaded it and copy paste in my project : 
https://pub.dev/packages/openid_client

**Comment by peterpoliwoda** [comment]
Hey @intako have you got an example usage of Keycloak within a Flutter app? I'm looking to include it in a nicely packaged networking service used within my app to use within other screens.
