### ISSUE TITLE
Feature Request - Support hybrid flow

### ISSUE THREAD

**Issue by torleifs** [Clancey/simple_auth#68]
If I understand the code correctly, simple_auth is currently hardcoded in  `WebAuthenticator`. In my use-case, I would like to use a hybrid flow to do auth with my own Identity Server and instead pass `code Id_token`.

**Comment by Clancey** [comment]
Nothing is hard coded. Any part can be overridden. It does default to what is needed for most providers.  However things like [Facebook](https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/providers/facebook.dart#L67) override things. https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/api/webAuthenticator.dart#L46-L71

**Comment by torleifs** [comment]
I was thinking about the `authCodeKey` in `WebAuthenticator`, but you are right, it can be modified.
However, this part:
https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/api/webAuthenticator.dart#L27-L40
is a bit problematic because it expects the query parameters to contain a parameter named the same as the content of 'authCodeKey`. If `authCodeKey` is "code id_token", this will fail since the authorization code will be in a parameter named `code` also when using hybrid flow.

Additionally, the comment above this method is a bit misleading as the method looks for *authorization codes*, not *tokens*.

**Comment by Clancey** [comment]
It's not a problem. You subclass and you can modify that behavior. You can change what gets passed in and what it's looking for!

**Comment by Clancey** [comment]
Feel free to re-open this if you still need help. Also if you just want to ask a few questions, the Gitter chat works great.
