### ISSUE TITLE
Custom Chrome Tabs

### ISSUE THREAD

**Issue by ermissa** [Clancey/simple_auth#74]
How can I open WebView screens inside app?

**Comment by ermissa** [comment]
I think I found the solution. I changed _useEmbeddedBrowser_ to **true** in _webAuthenticator.dart_

But then another issue arose. I will open another issue for it.

**Comment by Clancey** [comment]
So by default it uses Chrome Tabs. If you set useEmbeddedBrowser to true, it will present the UI internally. Chrome Tabs is more secure, but harder to use.

**Comment by ermissa** [comment]
If I set useEmbeddedBrowser to true, I am facing problem with google OICD authentication. My login page has an option to login with Google but when I click that Google is giving me **403:disallowed_useragent** error. See https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
