### ISSUE TITLE
Google Error: disallowed_useragent

### ISSUE THREAD

**Issue by ermissa** [Clancey/simple_auth#75]
In order to embed webview login screen to my app , I setted _useEmbeddedBrowser_ to true. My login page has an option to login with Google but when I click that Google is giving me **403:disallowed_useragent error.** 
See: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

I couldn't figure out how to overcome this problem.

**Comment by Clancey** [comment]
This is not something I can fix. Embedded web views are not secure, so google does what they can to prevents them. You should use the Chrome Tabs.
