### ISSUE TITLE
Just a little help -- Integration with Twitch ?? 

### ISSUE THREAD

**Issue by sjmcdowall** [Clancey/simple_auth#78]
Just hoping someone maybe has some pointers on how to use this library for integrating to the Twitch *user* level authorization (not the API Developer level) .. into my Flutter app (without a backend .. which is what is confusing me is how does the redirect back work?) .. 

I did read the docs .. but.. for someone totally new to OAUTH2 .. The documentation (for the NEW Twitch API) indicates it handles both "OIDC" and "OAUTH" flows .. but .. aren't they about the same things?  

Anyway -- any pointers to how this could work in my Flutter app would be highly appreciated!

Update -- well I am trying from the example code -- but I am getting an error when I compile:

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/sjm/play/mel/ios/Runner/AppDelegate.m:14:13: error: use of undeclared identifier 'SimpleAuthFlutterPlugin'
        return [SimpleAuthFlutterPlugin checkUrl:url];
                ^
    1 error generated.

I presume this is from adding the delegate logic as indicated in the documentation .. but .. maybe that isn't correct for Flutter??  Or maybe I did it wrong?

**Comment by Clancey** [comment]
I believe you have worked past this by adding the Import statement correct? Closing. Reopen if you need to.
