### ISSUE TITLE
azure ouauth failure

### ISSUE THREAD

**Issue by osorito** [Clancey/simple_auth#80]
If i tap login for azure, after adding the tennant id and the client id, the application gives this error.

flutter run -d 5830DC35-D7AA-496D-8971-F0F1D3A1CF4D
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           2.4s
 └─Compiling, linking and signing...                         2.8s
Xcode build done.                                            6.7s
Registered SimpleAuth on iOS
Syncing files to device iPhone X...                                     
 3,830ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild
state), press "R".
An Observatory debugger and profiler on iPhone X is available at:
http://127.0.0.1:62227/
For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
flutter: FormatException: Unexpected end of input (at character 1)

^
Authenticator created
presenting the authenticator
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d9766fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010cf1aac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d8c4ddc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010d9e59b4 -[__NSDictionaryM setObject:forKey:] + 1012
	4   Runner                              0x000000010a7e8414 __46+[SFSafariAuthenticator presentAuthenticator:]_block_invoke + 292
	5   libdispatch.dylib                   0x000000011082eccf _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x000000011082fd02 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000011083ba50 _dispatch_main_queue_callback_4CF + 1276
	8   CoreFoundation                      0x0000000<…>
Lost connection to device.

**Comment by Clancey** [comment]
That error doesn't really give much to go on. I am guessing it is something with the redirect url.

**Comment by osorito** [comment]
import 'package:flutter/material.dart';
import 'package:simple_auth/simple_auth.dart' as simpleAuth;
import 'package:simple_auth_flutter/simple_auth_flutter.dart';
//import 'package:simple_auth_flutter_example/api_definitions/youtubeApi.dart';

void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  initState() {
    super.initState();
    SimpleAuthFlutter.init(context);
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'SimpleAuth Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'SimpleAuth Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static String azureClientId = "074aa6cb-5c95-47";//removed for security
  static String azureTennant = "e50ebc84-76f2-46";//removed for security
  final simpleAuth.AzureADApi azureApi = new simpleAuth.AzureADApi(
      "azure",
      azureClientId,
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize",
     
      "https://login.microsoftonline.com/$azureTennant/oauth2/token",
      
      "https://management.azure.com/",
      "redirecturl");

  final simpleAuth.AmazonApi amazonApi = new simpleAuth.AmazonApi(
      "amazon",
      "amzn1.application-oa2-client.848f75b20206455097cde6b63ca53dec",
      "759db00c1a71fe308d55ce42387c510af8337a5b3aa402a835b77dc552766c3a",
      "http://localhost",
      scopes: ["clouddrive:read", "clouddrive:write"]);

  final simpleAuth.DropboxApi dropboxApi = new simpleAuth.DropboxApi(
      "dropbox", "51ekthoysn2mwno", "sscq5yu19uyt1kg", "http://localhost");

  final simpleAuth.FacebookApi facebookApi = new simpleAuth.FacebookApi(
    "facebook",
    "clientId",
    "clientSecret",
    "redirect",
  );

  final simpleAuth.GithubApi githubApi = new simpleAuth.GithubApi(
      "github", "clientId", "clientSecret", "redirect:/",
      scopes: [
        "user",
        "repo",
        "public_repo",
      ]);

  final simpleAuth.GoogleApi googleApi = new simpleAuth.GoogleApi("google",
      "992461286651-k3tsbcreniknqptanrugsetiimt0lkvo.apps.googleusercontent.com",
      "redirecturl",
      clientSecret: "avrYAIxweNZwcHpsBlIzTp04",
      scopes: [
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/userinfo.profile"
      ]);

  final simpleAuth.BasicAuthApi basicApi = new simpleAuth.BasicAuthApi(
      "github-basic", "https://api.github.com/user");
  final simpleAuth.InstagramApi instagramApi = new simpleAuth.InstagramApi(
      "instagram", "clientId", "clientSecret", "redirecturl");

  final simpleAuth.LinkedInApi linkedInApi = new simpleAuth.LinkedInApi(
      "linkedin", "clientId", "clientSecret", "redirecturl");

  final simpleAuth.MicrosoftLiveConnectApi microsoftLiveApi =
      new simpleAuth.MicrosoftLiveConnectApi(
          "microsoftconnect", "clientId", "clientSecret", "redirecturl");
  //final youtubeApi = new YoutubeApi("Youtube");
  @override
  Widget build(BuildContext context) {
    SimpleAuthFlutter.context = context;
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: new Text(widget.title),
      ),
      body: ListView(
        children: <Widget>[
          ListTile(
            title: Text(
              "AzureAD OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(azureApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(azureApi);
            },
          ),
          ListTile(
            title: Text(
              "Google OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () async {
              try {
                var user = await googleApi.getUserProfile();
                showMessage("${user.name} logged in");
              } catch (e) {
                showError(e);
              }
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(githubApi);
            },
          ),
          // ListTile(
          //   title: Text(
          //     "Youtube",
          //     style: Theme.of(context).textTheme.headline,
          //   ),
          // ),
          // ListTile(
          //   leading: Icon(Icons.launch),
          //   title: Text('Login'),
          //   onTap: () async {
          //     try {
          //       var user = await youtubeApi.getUserProfile();
          //       showMessage("${user.name} logged in");
          //     } catch (e) {
          //       showError(e);
          //     }
          //   },
          // ),
          // ListTile(
          //   leading: Icon(Icons.launch),

          //   title: Text('Search for "Flutter"'),
          //   onTap: () async {
          //     try {
          //       var user = await youtubeApi.search("flutter");
          //       print(user.body);
          //       showMessage(user.body.items.length.toString());
          //     } catch (e) {
          //       showError(e);
          //     }
          //   },
          // ),
          ListTile( 
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(githubApi);
            },
          ),
          ListTile(
            title: Text(
              "Amazon OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(amazonApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(amazonApi);
            },
          ),
          ListTile(
            title: Text(
              "Dropbox OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(dropboxApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(dropboxApi);
            },
          ),
          ListTile(
            title: Text(
              "Facebook OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(facebookApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(facebookApi);
            },
          ),
          ListTile(
            title: Text(
              "Github OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(githubApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(githubApi);
            },
          ),
          ListTile(
            title: Text(
              "Github BasicAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () async {
              try {
                var success = await basicApi.authenticate();
                showMessage("Logged in success: $success");
              } catch (e) {
                showError(e);
              }
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () async {
              await basicApi.logOut();
              showMessage("Logged out");
            },
          ),
          ListTile(
            title: Text(
              "Instagram OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(instagramApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(instagramApi);
            },
          ),
          ListTile(
            title: Text(
              "LinkedIn OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(linkedInApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(linkedInApi);
            },
          ),
          ListTile(
            title: Text(
              "Microsoft Live OAuth",
              style: Theme.of(context).textTheme.headline,
            ),
          ),
          ListTile(
            leading: Icon(Icons.launch),
            title: Text('Login'),
            onTap: () {
              login(microsoftLiveApi);
            },
          ),
          ListTile(
            leading: Icon(Icons.delete),
            title: Text('Logout'),
            onTap: () {
              logout(microsoftLiveApi);
            },
          ),
        ],
      ),
    );
  }

  void showError(dynamic ex) {
    showMessage(ex.toString());
  }

  void showMessage(String text) {
    var alert = new AlertDialog(content: new Text(text), actions: <Widget>[
      new FlatButton(
          child: const Text("Ok"),
          onPressed: () {
            Navigator.pop(context);
          })
    ]);
    showDialog(context: context, builder: (BuildContext context) => alert);
  }

  void login(simpleAuth.AuthenticatedApi api) async {
    try {
      var success = await api.authenticate();
      showMessage("Logged in success: $success");
    } catch (e) {
      showError(e);
    }
  }

  void logout(simpleAuth.AuthenticatedApi api) async {
    await api.logOut();
    showMessage("Logged out");
  }
}

**Comment by Clancey** [comment]
You didn't replace the "redirecturl". It cannot redirect back to your app: https://github.com/Clancey/simple_auth#redirect

**Comment by osorito** [comment]
I replaced the return url with https://login.live.com/oauth20_desktop.srf
Now it displays this error
{ "error": {"MissingApiVersionParameter","message": "The api-version query parameter (?api-version=) is required for all request. "}}

**Comment by osorito** [comment]
This is my AppDelegate.m file 

#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"


#import <simple_auth_flutter/SimpleAuthFlutterPlugin.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
    return [SimpleAuthFlutterPlugin checkUrl:url];
}

@end

**Comment by Clancey** [comment]
That Redirect can't work. There is no way for that to open your app, please check: https://github.com/Clancey/simple_auth#redirect

**Comment by osorito** [comment]
<img width="378" alt="Screen Shot 2019-04-17 at 3 10 39 PM" src="https://user-images.githubusercontent.com/22304375/56314467-2e4c1b00-6123-11e9-9b45-65765691875f.png">
<img width="388" alt="Screen Shot 2019-04-17 at 3 10 23 PM" src="https://user-images.githubusercontent.com/22304375/56314468-2e4c1b00-6123-11e9-8320-bf6f7b8c8f74.png">

**Comment by osorito** [comment]
This is the output in the terminal 

flutter run -d 5830DC35-D7AA-496D-8971-F0F1D3A1CF4D
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                              1.2s
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           1.5s
 └─Compiling, linking and signing...                         4.4s
Xcode build done.                                            7.3s
Registered SimpleAuth on iOS
Syncing files to device iPhone X...                              1,944ms

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild
state), press "R".
An Observatory debugger and profiler on iPhone X is available at:
http://127.0.0.1:50698/
For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
flutter: FormatException: Unexpected end of input (at character 1)

^
Authenticator created
presenting the authenticator

**Comment by tabinnorway** [comment]
I am having the same issue with MissingApiVersionparameter.
- My redirect URL is set to customScheme://com.myapp.foo in the Azure portal - seems that's the requirement from Azure.
- It is then set to com.myapp.foo:/redirct in the AzureADApi constructor.
- Finally, I am registering the custom scheme in AndroidManifest.xml as so:
<data android:scheme="com.myapp.foo" />

I am obviously doing something incorrectly. Any ideas?

**Comment by lukelima** [comment]
Same issue :/

**Comment by abuzarsaddiqui** [comment]
I have tried this and it works but gives 404 Error at the end after sign in.

1. First create a client secret and then pass it in constructor.
2. Rearrange the parameters as Follows

`final simpleAuth.AzureADApi azureApi = new simpleAuth.AzureADApi(

      "azure",
      "AZURE CLIENT ID",
      "https://login.microsoftonline.com/YOUR TANNENT ID/oauth2/token",
      "https://management.azure.com/",
      "https://login.microsoftonline.com/YOUR TANNENT ID/oauth2/authorize",
      "YOUR REDIRECT URL",
        clientSecret: "YOUR CLIENT SECRET");

`

**Comment by CoreyCole** [comment]
So we don't need to define the `SimpleAuthCallbackActivity`, right? That activity is defined for us by the simple_auth plugin. We just need to point to it in the android manifest (`android/app/src/main/AndroidManifest.xml`)

https://github.com/Clancey/simple_auth/blob/85b6afc2aa52dc521a01577b3d6c5f06ce9cff05/simple_auth_flutter/android/src/main/java/clancey/simpleauth/simpleauthflutter/SimpleAuthCallbackActivity.java
```java
package clancey.simpleauth.simpleauthflutter;

import android.app.Activity;
import android.os.Bundle;

public class SimpleAuthCallbackActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        CustomTabsAuthenticator.onActivityResult(getIntent());
        finish();
    }
}
```
