### ISSUE TITLE
Azure login

### ISSUE THREAD

**Issue by osorito** [Clancey/simple_auth#82]
I'm trying the example you have online, so far I've made it log into my company but at the end I get a white screen 
<img width="379" alt="login live" src="https://user-images.githubusercontent.com/22304375/56378245-724e2700-61da-11e9-801d-4901ff9186c7.png">

This is my code 
  static String azureClientId = "caa16c9f-xxxxx;
  static String azureTennant = "e50ebc8xxxxxxxxxx";
  final simpleAuth.AzureADApi azureApi = new simpleAuth.AzureADApi(
      "azure",
      azureClientId,
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize",
      "https://login.microsoftonline.com/$azureTennant/oauth2/token",
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize?response_type=id_token&client_id=$azureClientId",
      "https://login.live.com/oauth20_desktop.srf"
    // "https://login.microsoftonline.com/common/oauth2/nativeclient"
      );

Am I missing something?

**Comment by Clancey** [comment]
Yes, HTTP Redirects don't work: https://github.com/Clancey/simple_auth#redirect

**Comment by osorito** [comment]
<img width="378" alt="login microsoft" src="https://user-images.githubusercontent.com/22304375/56379575-0372cd00-61de-11e9-8c35-72b6214563fd.png">
I tried following the example and used the bundle identifier like this 

final simpleAuth.AzureADApi azureApi = new simpleAuth.AzureADApi(
      "azure",
      azureClientId,
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize",
      "https://login.microsoftonline.com/$azureTennant/oauth2/token",
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize?response_type=id_token&client_id=$azureClientId",
      //"https://login.live.com/oauth20_desktop.srf"
     //"https://login.microsoftonline.com/common/oauth2/nativeclient"
     "com.example.testAzure2:/redirect"

      );

But I get the following screen.

**Comment by Clancey** [comment]
It could be an issue with your client id/secret, Depending on how you set it up. Did you register the new redirect? Did you setup scopes via the azure portal and the client id? Or do you need to pass in the scopes. Its really hard to say. You can also try [AzureADV2](https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/providers/azureADV2.dart)

**Comment by osorito** [comment]
The way I create the app in https://portal.azure.com is as follows.
Name : FlutterApp
Application Type : tried both native app and web
in Redirect url I use this value https://login.live.com/oauth20_desktop.srf
I copied the redirect url from this page https://pub.dartlang.org/packages/aad_oauth.

Must likely the way I set up the app is wrong, could you guide me? The package you made so far works as intended, must likely is an issue on the way I created the app in the portal.

**Comment by Clancey** [comment]
That redirect cannot work, it has to match. So use "com.example.testAzure2:/redirect"

**Comment by osorito** [comment]
Deleted the app from portal, created a new one with com.example.testAzure2://redirect as the return url and the code is 
 final simpleAuth.AzureADApi azureApi = new simpleAuth.AzureADApi(
      "azure",
      azureClientId,
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize",
      "https://login.microsoftonline.com/$azureTennant/oauth2/token",
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize?response_type=id_token&client_id=$azureClientId",
      //"https://login.live.com/oauth20_desktop.srf"
     //"https://login.microsoftonline.com/common/oauth2/nativeclient"
     //"com.example.testAzure2:/redirect"
     //"msalcaa16c9f-3f15-4144-8ab2-575358addf18://auth"
     "com.example.testAzure2://redirect"
      );
<img width="388" alt="login error" src="https://user-images.githubusercontent.com/22304375/56387950-b699f100-61f3-11e9-949c-de1c70b624cb.png">
But I get this error.

**Comment by Clancey** [comment]
It is failing this check, https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/api/webAuthenticator.dart#L30

You can put a break point and step through to see why it fails.

**Comment by osorito** [comment]
I even modified the manifest to allow token and id .

{
	"id": "4bf97f14596c",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": 2,
	"addIns": [],
	"allowPublicClient": true,
	"appId": "750b6f",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2019-04-18T20:10:08Z",
	"groupMembershipClaims": null,
	"identifierUris": [],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "FlutterMobileApp",
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": true,
	"oauth2Permissions": [],
	"oauth2RequirePostResponse": true,
	"optionalClaims": null,
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [],
	"preAuthorizedApplications": [],
	"publisherDomain": "xxxxx",
	"replyUrlsWithType": [
		{
			"url": "com.example.testAzure2://redirect",
			"type": "InstalledClient"
		},
		{
			"url": "https://login.live.com/oauth20_desktop.srf",
			"type": "InstalledClient"
		},
		{
			"url": "urn:ietf:wg:oauth:2.0:oob",
			"type": "InstalledClient"
		},
		{
			"url": "https://login.microsoftonline.com/common/oauth2/nativeclient",
			"type": "InstalledClient"
		},
		{
			"url": "msal2837a9e09-afe7-e3c1f0750b6f://auth",
			"type": "InstalledClient"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "39da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADandPersonalMicrosoftAccount",
	"tags": [],
	"tokenEncryptionKeyId": null
}

**Comment by osorito** [comment]
Authenticator created
presenting the authenticator
flutter: url here com.example.testazure2://redirect/?error=invalid_resource&error_description=AADSTS500011%3A+The+resource+principal+named+https%3A%2F%2Flogin.microsoftonline.com%2Fe50ebc50-c3f7abc924af%2Foauth2%2Ftoken+was+not+found+in+the+tenant+named+e-b550-c3f7abc924af.+This+can+happen+if+the+application+has+not+been+installed+by+the+administrator+of+the+tenant+or+consented+to+by+any+user+in+the+tenant.+You+might+have+sent+your+authentication+request+to+the+wrong+tenant.%0D%0ATrace+ID%3A+ca2c41ea-21ad-40ac-9bbe-6169a0c69000%0D%0ACorrelation+ID%3A+e3706dbd-b86b-4230-ba1d-c43a9efe9ec9%0D%0ATimestamp%3A+2019-04-18+23%3A38%3A08Z

**Comment by Clancey** [comment]
I think you need scopes, or to set allowed resources when setting up the client

**Comment by osorito** [comment]
In azure portal I created a scope and set authorized client. On the code can I tell it the scope?

**Comment by Clancey** [comment]
yes, 

```
new simpleAuth.AzureADApi(
"azure",
azureClientId,
"https://login.microsoftonline.com/$azureTennant/oauth2/authorize",
"https://login.microsoftonline.com/$azureTennant/oauth2/token",
"https://login.microsoftonline.com/$azureTennant/oauth2/authorize?response_type=id_token&client_id=$azureClientId",
"com.example.testAzure2://redirect"
){scopes ... };
```

**Comment by osorito** [comment]
I ended up using this package aad_oauth. You should check the package, this one without modifying the portal runs with just specifying the client id, tenant id and return url which basically is the bundle id ://redirect . Thanks for your time.

**Comment by osorito** [comment]
This is the only way I found to make it work but you will need admin permission in the Azure portal

  final simpleAuth.AzureADApi azureApi = new simpleAuth.AzureADApi(
      "azure",
      azureClientId,
      "https://login.microsoftonline.com/$azureTennant/oauth2/authorize",
      "https://login.microsoftonline.com/$azureTennant/oauth2/token",
      "https://login.microsoftonline.com/$azureTennant/adminconsent?client_id=$azureClientId&admin_consent=False",
      "com.example.testAzure2://redirect",
      scopes: [
        "openid",
        "profile",
        "offline_access",
      ]
      );

**Comment by furkanvatandas** [comment]
I get "Unable to get an AuthToken from server" error. Are there any changes in source code?

**Comment by Clancey** [comment]
@furkanvatandas  Do you have offline access in your scopes?

**Comment by lukelima** [comment]
Hi Clancey! Got the same error as @furkanvatandas :  I get "Unable to get an AuthToken from server" error." and I do have offline access in my scopes. What can I do ?
