### ISSUE TITLE
FormatException error

### ISSUE THREAD

**Issue by titonton** [Clancey/simple_auth#83]
I'm having an issue with the response after I'm authenticated. It looks like it is returning exactly what I need, but I'm guessing it's expecting a JSON object instead whatever this is. This is the exception I keep getting

FormatException: Unexpected character (at character 1)
access_token={accessToken}&expires_in=28800
^
{accessToken} shows the actual token. I just replaced it for the sake of posting it here. My redirect url is good. I'm using the same configuration in another project in Xamarin with the same URLScheme on iOS. It works on the project, but obviously not here. Is there something I'm missing? Let me know what you need from me. Thanks.

**Comment by Clancey** [comment]
Do you have a line number where this is blowing up?

**Comment by titonton** [comment]
Line 19 of authenticatedAPI.dart. The authenticate() function

**Comment by sjmcdowall** [comment]
Ah ha! I am seeing this too -- was wondering where it was from...

**Comment by titonton** [comment]
So I'm still having this problem. Does the response have to be in json format?

**Comment by titonton** [comment]
Apologies I was mistaken. The error gets thrown in oauthApi.dart line 118. It tries to convert the string "access_token={accessToken}&expires_in=28800" expecting it to be in a json format when it's not. I'm guessing I would have to use my own converter to convert the string?

**Comment by titonton** [comment]
I just wrote a test with the line with the exact string that was coming back and they passed. I'm not sure why this exception is still being thrown
```dart
test('Testing Json decoding', (){
    var testString = "access_token=AT-sldkn-alskvnalsnv-dlfjvnsjkvn&expires_in=28800&refresh_token=RT-blahblablahblahblablahblahblablahblahblablahblahblablah";
    
    var map = convert.json.encode(testString);

    expect(map.contains("access_token"), true);
  });
```

**Comment by titonton** [comment]
Should I open a new issue for this?

**Comment by titonton** [comment]
Can this issue be reopened?

**Comment by titonton** [comment]
I'm gonna go ahead and close this. The data should be coming in as a JSON object anyways. I'll have it transformed on the server side. Thanks anyways! Great package by the way.
