### ISSUE TITLE
How to use custom authenticator with generator

### ISSUE THREAD

**Issue by esskar** [Clancey/simple_auth#91]
First, great library, thanks for all your effort.

Now, my problem. I am trying to authenticate against Spotify. The auth process works, but it looks like it fails to understand the response.

```
@OAuthApiDeclaration(
  "SpotifyApi", 
  "12345", 
  "", 
  "https://accounts.spotify.com/api/token", 
  "https://accounts.spotify.com/authorize", 
  "myapp://auth/",
  scopes: ["user-read-private", "user-read-email"])
abstract class SpotifyDefinition {

}
```

but the user is never valid

```
var user = await api.authenticate();
return user.isValid();
```

Spotify passes the result token as `myapp://auth/?code=23456789`, how can i parse that correctly?

**Comment by Clancey** [comment]
That should work, if your getting to the point of getting the user, it should work. You could put a few break points in to see why it is not valid. https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/oauth/oauthAccount.dart#L28

This is where the account is created: https://github.com/Clancey/simple_auth/blob/master/simple_auth/lib/src/oauth/oauthApi.dart#L120

**Comment by esskar** [comment]
Ok, using the right client secret solved my problem. thanks for the help. 👍
